Repository EarnedIt-team/Earned-it, pull requests merged in 2025-07, with the labels that each got.

#7 Chore/docker 도커 로컬 개발 환경 구성, 프로젝트 이름 변경
  Dockerfile
  docker-compose.yml
  settings.gradle
  src/main/java/_team/earnedit/EarneditApplication.java
  src/main/java/_team/earnedit/config/CorsConfig.java
  src/main/java/_team/earnedit/config/SwaggerConfig.java
  src/main/java/_team/earnedit/controller/HealthCheckController.java
  src/main/java/_team/earnedit/global/ApiResponse.java
  src/main/java/_team/earnedit/global/ErrorCode.java
  src/main/java/_team/earnedit/global/ErrorResponse.java
  src/main/java/_team/earnedit/global/exception/GlobalExceptionHandler.java
  src/test/java/_team/earnedit/EarneditApplicationTests.java
Labels: 환경 세팅

#9 Fix/profile-separate 스프링 프로필 dev, prod 분리
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application.yaml
Labels: 환경 세팅

#10 Chore/docker-separate 도커 운영, 개발환경 분리 및 스크립트 파일 추가
  docker-compose.dev.yml
  docker-compose.prod.yml
  start-dev.sh
Labels: 환경 세팅

#13 Feat/signup : 수익 정보 생성 api, 초수익 스케줄러, 이메일토큰검증에 토큰-이메일 검증 추가
  src/main/java/_team/earnedit/EarneditApplication.java
  src/main/java/_team/earnedit/controller/EmailVerificationController.java
  src/main/java/_team/earnedit/controller/ProfileController.java
  src/main/java/_team/earnedit/dto/auth/EmailTokenVerifyRequestDto.java
  src/main/java/_team/earnedit/dto/profile/SalaryRequestDto.java
  src/main/java/_team/earnedit/dto/profile/SalaryResponseDto.java
  src/main/java/_team/earnedit/entity/Salary.java
  src/main/java/_team/earnedit/global/ErrorCode.java
  src/main/java/_team/earnedit/global/scheduler/AmountPerSecScheduler.java
  src/main/java/_team/earnedit/global/util/SalaryCalculator.java
  src/main/java/_team/earnedit/repository/SalaryRepository.java
  src/main/java/_team/earnedit/service/EmailVerificationService.java
  src/main/java/_team/earnedit/service/ProfileService.java
Labels: 기능

#16 Chore: 배포된 도메인 서버 Mixed Content 문제 수정 2
  src/main/resources/application.yaml
Labels: 환경 세팅

#20 fix : docker-compose.prod.yml 에서 공통네트워크설정
  docker-compose.prod.yml
Labels: 버그

#21 Feat/wish-c 위시 아이템 생성 API
  build.gradle
  docker-compose.dev.yml
  src/main/java/_team/earnedit/controller/WishController.java
  src/main/java/_team/earnedit/dto/wish/WishAddRequest.java
  src/main/java/_team/earnedit/dto/wish/WishAddResponse.java
  src/main/java/_team/earnedit/entity/Wish.java
  src/main/java/_team/earnedit/global/ErrorCode.java
  src/main/java/_team/earnedit/global/exception/GlobalExceptionHandler.java
  src/main/java/_team/earnedit/repository/WishRepository.java
  src/main/java/_team/earnedit/service/WishService.java
  src/main/resources/application.yaml
Labels: 기능

#22 Feat/wish-r 위시리스트 조회 API
  src/main/java/_team/earnedit/controller/WishController.java
  src/main/java/_team/earnedit/dto/wish/WishResponse.java
  src/main/java/_team/earnedit/global/ErrorCode.java
  src/main/java/_team/earnedit/global/exception/wish/WishException.java
  src/main/java/_team/earnedit/repository/WishRepository.java
  src/main/java/_team/earnedit/service/WishService.java
Labels: 기능

#23 Feat/wish-u 위시 업데이트 API
  src/main/java/_team/earnedit/controller/WishController.java
  src/main/java/_team/earnedit/dto/wish/WishUpdateRequest.java
  src/main/java/_team/earnedit/dto/wish/WishUpdateResponse.java
  src/main/java/_team/earnedit/entity/Wish.java
  src/main/java/_team/earnedit/global/ErrorCode.java
  src/main/java/_team/earnedit/service/WishService.java
Labels: 기능

#24 Feat/wish-d 삭제 API 추가
  src/main/java/_team/earnedit/controller/WishController.java
  src/main/java/_team/earnedit/global/ErrorCode.java
  src/main/java/_team/earnedit/service/WishService.java
Labels: 기능

#25 Feat/wish-read-1 위시 단일 조회 API
  src/main/java/_team/earnedit/controller/WishController.java
  src/main/java/_team/earnedit/service/WishService.java
Labels: 기능

#26 Feat/social login : 카카오 로그인 api 구현
  src/main/java/_team/earnedit/controller/AuthController.java
  src/main/java/_team/earnedit/dto/auth/SignUpRequestDto.java
  src/main/java/_team/earnedit/dto/socialLogin/KakaoSignInRequestDto.java
  src/main/java/_team/earnedit/dto/socialLogin/KakaoUserInfoDto.java
  src/main/java/_team/earnedit/entity/User.java
  src/main/java/_team/earnedit/global/ErrorCode.java
  src/main/java/_team/earnedit/repository/UserRepository.java
  src/main/java/_team/earnedit/service/AuthService.java
  src/main/java/_team/earnedit/service/socialLogin/KakaoOAuthService.java
Labels: 기능

#29 Feat/star Star 상태 업데이트 API, 조회 API 구현
  src/main/java/_team/earnedit/controller/StarController.java
  src/main/java/_team/earnedit/controller/WishController.java
  src/main/java/_team/earnedit/dto/wish/WishListResponse.java
  src/main/java/_team/earnedit/entity/Star.java
  src/main/java/_team/earnedit/entity/Wish.java
  src/main/java/_team/earnedit/global/ErrorCode.java
  src/main/java/_team/earnedit/global/exception/star/StarException.java
  src/main/java/_team/earnedit/repository/StarRepository.java
  src/main/java/_team/earnedit/repository/WishRepository.java
  src/main/java/_team/earnedit/service/StarService.java
  src/main/java/_team/earnedit/service/WishService.java
Labels: 기능

#31 Feat/social apple : 애플 소셜로그인(회원가입) api 구현 (+ redis로 공개키 관리)
  build.gradle
  src/main/java/_team/earnedit/controller/AuthController.java
  src/main/java/_team/earnedit/dto/socialLogin/AppleSignInRequestDto.java
  src/main/java/_team/earnedit/dto/socialLogin/AppleUserInfoDto.java
  src/main/java/_team/earnedit/dto/socialLogin/KakaoUserInfoDto.java
  src/main/java/_team/earnedit/global/ErrorCode.java
  src/main/java/_team/earnedit/global/exception/OAuth/OAuthException.java
  src/main/java/_team/earnedit/global/jwt/ExternalJwtUtil.java
  src/main/java/_team/earnedit/service/AuthService.java
  src/main/java/_team/earnedit/service/socialLogin/AppleOAuthService.java
  src/main/java/_team/earnedit/service/socialLogin/KakaoOAuthService.java
Labels: 기능

#32 ref : 이메일 unique 조건 삭제 (자체회원가입 서비스단에서 검증 이미 있음)
  src/main/java/_team/earnedit/entity/User.java
Labels: 리팩터링

#35 Ref/response : 로그인 response dto 변경
  src/main/java/_team/earnedit/controller/AuthController.java
  src/main/java/_team/earnedit/dto/auth/SignInResponseDto.java
  src/main/java/_team/earnedit/repository/TermRepository.java
  src/main/java/_team/earnedit/service/AuthService.java
Labels: 리팩터링

#36 fix : 자체로그인시 이메일 찾을 때 provider 같이 조회
  src/main/java/_team/earnedit/repository/UserRepository.java
  src/main/java/_team/earnedit/service/AuthService.java
Labels: 버그

#38 Feat/user delete : 유저 탈퇴api, 탈퇴한 유저 복구로직, 탈퇴정책 로직 스케줄러 구현
  src/main/java/_team/earnedit/controller/UserController.java
  src/main/java/_team/earnedit/entity/User.java
  src/main/java/_team/earnedit/global/ErrorCode.java
  src/main/java/_team/earnedit/global/scheduler/UserCleanupScheduler.java
  src/main/java/_team/earnedit/repository/UserRepository.java
  src/main/java/_team/earnedit/service/AuthService.java
  src/main/java/_team/earnedit/service/UserService.java
Labels: 기능

#39 Feat/salary : 1유저당 1 salary data로 수정(덮어쓰기로직), 수익조회 api 구현
  src/main/java/_team/earnedit/controller/ProfileController.java
  src/main/java/_team/earnedit/entity/Salary.java
  src/main/java/_team/earnedit/service/ProfileService.java
Labels: 리팩터링, 기능

#40 Doc/swagger 위시, Star, 헬스체크, 메인페이지 스웨거 문서화
  src/main/java/_team/earnedit/controller/FileUploadController.java
  src/main/java/_team/earnedit/controller/MainController.java
  src/main/java/_team/earnedit/controller/StarController.java
  src/main/java/_team/earnedit/controller/WishController.java
  src/main/java/_team/earnedit/dto/main/MainPageResponse.java
  src/main/java/_team/earnedit/dto/wish/WishAddRequest.java
  src/main/java/_team/earnedit/dto/wish/WishAddResponse.java
  src/main/java/_team/earnedit/dto/wish/WishDetailResponse.java
  src/main/java/_team/earnedit/dto/wish/WishListResponse.java
  src/main/java/_team/earnedit/dto/wish/WishUpdateRequest.java
  src/main/java/_team/earnedit/dto/wish/WishUpdateResponse.java
  src/main/java/_team/earnedit/global/healthcheck/HealthCheckController.java
  src/main/java/_team/earnedit/repository/WishRepository.java
  src/main/java/_team/earnedit/service/WishService.java
Labels: 문서

#41 ref: SALARY_NOT_FOUND 예외처리 제거
  src/main/java/_team/earnedit/service/MainService.java
Labels: 리팩터링
