Repository EarnedIt-team/Earned-it, pull requests merged in 2025-09, with the labels that each got.

#84 Feat/report : 공개범위 전환 api, 타유저신고api (신고남용방지 로직)
  src/main/java/_team/earnedit/controller/ProfileController.java
  src/main/java/_team/earnedit/controller/ReportController.java
  src/main/java/_team/earnedit/dto/profile/UpdateVisibilityRequestDto.java
  src/main/java/_team/earnedit/dto/report/ReportUserRequestDto.java
  src/main/java/_team/earnedit/entity/ReportReason.java
  src/main/java/_team/earnedit/entity/User.java
  src/main/java/_team/earnedit/entity/UserReport.java
  src/main/java/_team/earnedit/global/ErrorCode.java
  src/main/java/_team/earnedit/global/exception/report/ReportException.java
  src/main/java/_team/earnedit/repository/ReportReasonRepository.java
  src/main/java/_team/earnedit/repository/UserReportRepository.java
  src/main/java/_team/earnedit/service/ProfileService.java
  src/main/java/_team/earnedit/service/ReportService.java
Labels: 기능

#87 25.09.07 dev -> main merge
  src/main/java/_team/earnedit/dto/profile/OtherUserProfileResponse.java
  src/main/java/_team/earnedit/dto/profile/ProfileWithStarResponse.java
  src/main/java/_team/earnedit/service/ProfileService.java
Labels: 버그

#88 Feat/rank 랭킹 점수 지급 로직 + 랭킹 페이지 조회 응답 수정
  src/main/java/_team/earnedit/dto/rank/UserRankInfo.java
  src/main/java/_team/earnedit/entity/User.java
  src/main/java/_team/earnedit/repository/PuzzleSlotRepository.java
  src/main/java/_team/earnedit/service/DailyCheckService.java
  src/main/java/_team/earnedit/service/RankService.java
Labels: 기능

#92 doc: dev에 readme 병합 (같은 내용)
  README.md
Labels: 중복, 수정x

#95 Revert/bad prs : revert
  src/main/java/_team/earnedit/dto/rank/UserRankInfo.java
  src/main/java/_team/earnedit/dto/rank/UserRankRow.java
  src/main/java/_team/earnedit/entity/User.java
  src/main/java/_team/earnedit/repository/PuzzleSlotRepository.java
  src/main/java/_team/earnedit/repository/UserRepository.java
  src/main/java/_team/earnedit/service/DailyCheckService.java
  src/main/java/_team/earnedit/service/RankService.java
Labels: 버그

#103 hide : 찬영님 코드 주석 처리 2
  src/main/java/_team/earnedit/controller/ProductController.java
  src/main/java/_team/earnedit/repository/SearchItemRepository.java
  src/main/java/_team/earnedit/service/ProductService.java
Labels: 버그

#104 Dev -> main 09.15 2차 병합 시도 (상품검색API 주석처리)
  build.gradle
  src/main/java/_team/earnedit/controller/ProductController.java
  src/main/java/_team/earnedit/dto/item/NaverProductResponse.java
  src/main/java/_team/earnedit/dto/item/NaverProductSearchRequest.java
  src/main/java/_team/earnedit/dto/item/ProductSearchResponse.java
  src/main/java/_team/earnedit/dto/rank/UserRankInfo.java
  src/main/java/_team/earnedit/entity/SearchItem.java
  src/main/java/_team/earnedit/global/ErrorCode.java
  src/main/java/_team/earnedit/global/exception/email/EmailException.java
  src/main/java/_team/earnedit/repository/SearchItemRepository.java
  src/main/java/_team/earnedit/repository/UserReportRepository.java
  src/main/java/_team/earnedit/repository/UserRepository.java
  src/main/java/_team/earnedit/service/EmailService.java
  src/main/java/_team/earnedit/service/FileUploadService.java
  src/main/java/_team/earnedit/service/NaverShoppingService.java
  src/main/java/_team/earnedit/service/ProductService.java
  src/main/java/_team/earnedit/service/ProfileService.java
  src/main/java/_team/earnedit/service/RankService.java
  src/main/java/_team/earnedit/service/ReportService.java
  src/main/java/_team/earnedit/service/WishService.java
  src/main/resources/application.yaml
Labels: 버그

#106 bug : 상품 검색 API 복구 및 API 요청 형식 변경
  src/main/java/_team/earnedit/controller/ProductController.java
  src/main/java/_team/earnedit/dto/item/NaverProductSearchRequest.java
  src/main/java/_team/earnedit/dto/main/MainPageResponse.java
  src/main/java/_team/earnedit/entity/User.java
  src/main/java/_team/earnedit/mapper/MainPageMapper.java
  src/main/java/_team/earnedit/repository/PuzzleSlotRepository.java
  src/main/java/_team/earnedit/repository/SearchItemRepository.java
  src/main/java/_team/earnedit/service/DailyCheckService.java
  src/main/java/_team/earnedit/service/NaverShoppingService.java
  src/main/java/_team/earnedit/service/ProductService.java
  src/main/java/_team/earnedit/service/RewardCheckInService.java
Labels: 리팩터링

#108 ref: 2글자 닉네임 랭크 페이지에서 동* 과 같이 나타내도록 수정
  src/main/java/_team/earnedit/service/RankService.java
Labels: 리팩터링

#110 ref: 2글자 닉네임 랭크 페이지에서 동* 과 같이 나타내도록 수정
  src/main/java/_team/earnedit/service/RankService.java
Labels: 리팩터링

#117 Dev-> 09.17 위시 관련 버그 수정 및 응답 필드 추가(생성일, 수정일)
  src/main/java/_team/earnedit/controller/WishController.java
  src/main/java/_team/earnedit/dto/star/StarSummaryResponse.java
  src/main/java/_team/earnedit/service/ProfileService.java
  src/main/java/_team/earnedit/service/WishService.java
Labels: 리팩터링

#119 dev -> main 09.22 배경제거 서버 화이트리스트 적용
  src/main/java/_team/earnedit/config/security/SecurityConfig.java
Labels: 기능

#123 Revert firebase 적용 이후 DB연결 문제 발생, 정상 동작하던 커밋으로 롤백
  src/main/java/_team/earnedit/config/security/SecurityConfig.java
Labels: 버그
