Repository EarnedIt-team/Earned-it, pull requests merged in 2025-08, with the labels that each got.

#42 Feat/password : 비밀번호 변경 api, 비밀번호변경이메일 인증 api, 비밀번호변경이메일 검증 api
  src/main/java/_team/earnedit/controller/PasswordResetController.java
  src/main/java/_team/earnedit/dto/auth/PasswordResetRequestDto.java
  src/main/java/_team/earnedit/dto/auth/PasswordResetTokenVerifyRequestDto.java
  src/main/java/_team/earnedit/entity/PasswordResetToken.java
  src/main/java/_team/earnedit/entity/User.java
  src/main/java/_team/earnedit/global/ErrorCode.java
  src/main/java/_team/earnedit/global/util/EmailUtils.java
  src/main/java/_team/earnedit/repository/PasswordResetTokenRepository.java
  src/main/java/_team/earnedit/service/EmailService.java
  src/main/java/_team/earnedit/service/EmailVerificationService.java
  src/main/java/_team/earnedit/service/PasswordResetService.java
Labels: 리팩터링, 기능

#43 Feat/puzzle 도감 정보 조회 API, 조각 정보 조회, 추가 API 등
  src/main/java/_team/earnedit/controller/DailyCheckController.java
  src/main/java/_team/earnedit/controller/PuzzleController.java
  src/main/java/_team/earnedit/dto/main/MainPageResponse.java
  src/main/java/_team/earnedit/dto/puzzle/PieceResponse.java
  src/main/java/_team/earnedit/dto/puzzle/PuzzleResponse.java
  src/main/java/_team/earnedit/entity/Item.java
  src/main/java/_team/earnedit/entity/Piece.java
  src/main/java/_team/earnedit/entity/PuzzleSlot.java
  src/main/java/_team/earnedit/entity/Rarity.java
  src/main/java/_team/earnedit/entity/Theme.java
  src/main/java/_team/earnedit/global/ErrorCode.java
  src/main/java/_team/earnedit/global/exception/item/ItemException.java
  src/main/java/_team/earnedit/global/exception/piece/PieceException.java
  src/main/java/_team/earnedit/repository/ItemRepository.java
  src/main/java/_team/earnedit/repository/PieceRepository.java
  src/main/java/_team/earnedit/repository/PuzzleSlotRepository.java
  src/main/java/_team/earnedit/service/DailyCheckService.java
  src/main/java/_team/earnedit/service/MainService.java
  src/main/java/_team/earnedit/service/PuzzleService.java
Labels: 기능

#44 Ref/mainpage (프론트 요청) mainPage, 위시 추가 수정
  src/main/java/_team/earnedit/dto/wish/WishAddRequest.java
  src/main/java/_team/earnedit/service/MainService.java
  src/main/java/_team/earnedit/service/WishService.java
Labels: 기능

#45 Feat/star-order-save Top5 순서 변경 API
  src/main/java/_team/earnedit/controller/StarController.java
  src/main/java/_team/earnedit/dto/star/StarListResponse.java
  src/main/java/_team/earnedit/dto/star/StarOrderUpdateRequest.java
  src/main/java/_team/earnedit/entity/Star.java
  src/main/java/_team/earnedit/global/ErrorCode.java
  src/main/java/_team/earnedit/repository/StarRepository.java
  src/main/java/_team/earnedit/service/StarService.java
Labels: 기능

#47 Feat/search-wish 위시 검색 및 필터링 API
  build.gradle
  src/main/java/_team/earnedit/config/QueryDslConfig.java
  src/main/java/_team/earnedit/controller/WishController.java
  src/main/java/_team/earnedit/dto/PagedResponse.java
  src/main/java/_team/earnedit/dto/wish/WishSearchCondition.java
  src/main/java/_team/earnedit/global/ErrorCode.java
  src/main/java/_team/earnedit/repository/WishRepository.java
  src/main/java/_team/earnedit/service/WishService.java
Labels: 기능

#51 bug: price 단위 int -> long으로 수정
  src/main/java/_team/earnedit/dto/star/StarListResponse.java
  src/main/java/_team/earnedit/dto/wish/WishDetailResponse.java
  src/main/java/_team/earnedit/dto/wish/WishListResponse.java
  src/main/java/_team/earnedit/dto/wish/WishUpdateResponse.java
  src/main/java/_team/earnedit/entity/Wish.java
Labels: 버그

#52 Feat/adimin-page 관리자 페이지 작업, 위시 업데이트 버그 수정
  build.gradle
  src/main/java/_team/earnedit/config/security/SecurityConfig.java
  src/main/java/_team/earnedit/controller/admin/AdminDashboardController.java
  src/main/java/_team/earnedit/controller/admin/ItemAdminController.java
  src/main/java/_team/earnedit/controller/admin/PuzzleSlotAdminApiController.java
  src/main/java/_team/earnedit/controller/admin/PuzzleSlotAdminController.java
  src/main/java/_team/earnedit/dto/puzzle/PuzzleSlotForm.java
  src/main/java/_team/earnedit/dto/puzzle/PuzzleSlotResponse.java
  src/main/java/_team/earnedit/dto/puzzle/PuzzleSlotSwapRequest.java
  src/main/java/_team/earnedit/dto/wish/WishUpdateRequest.java
  src/main/java/_team/earnedit/entity/PuzzleSlot.java
  src/main/java/_team/earnedit/entity/Theme.java
  src/main/java/_team/earnedit/entity/Wish.java
  src/main/java/_team/earnedit/repository/PuzzleSlotRepository.java
  src/main/java/_team/earnedit/service/WishService.java
  src/main/java/_team/earnedit/service/admin/PuzzleSlotService.java
  src/main/java/_team/earnedit/service/admin/item/ItemService.java
  src/main/java/_team/earnedit/service/admin/item/ItemServiceImpl.java
  src/main/resources/application.yaml
  src/main/resources/static/images/placeholder.png
  src/main/resources/templates/admin/dashboard.html
  src/main/resources/templates/admin/item-form.html
  src/main/resources/templates/admin/item-list.html
  src/main/resources/templates/admin/puzzle-slot-form.html
  src/main/resources/templates/admin/puzzle-slot-grid.html
  src/main/resources/templates/admin/puzzle-slot-list.html
Labels: 기능

#56 Doc/swagger : 스웨거 문서화 작업
  src/main/java/_team/earnedit/controller/AuthController.java
  src/main/java/_team/earnedit/controller/EmailVerificationController.java
  src/main/java/_team/earnedit/controller/PasswordResetController.java
  src/main/java/_team/earnedit/controller/ProfileController.java
  src/main/java/_team/earnedit/controller/UserController.java
  src/main/java/_team/earnedit/dto/auth/EmailTokenVerifyRequestDto.java
  src/main/java/_team/earnedit/dto/auth/PasswordResetRequestDto.java
  src/main/java/_team/earnedit/dto/auth/PasswordResetTokenVerifyRequestDto.java
  src/main/java/_team/earnedit/dto/auth/RefreshResponseDto.java
  src/main/java/_team/earnedit/dto/auth/SignInRequestDto.java
  src/main/java/_team/earnedit/dto/auth/SignInResponseDto.java
  src/main/java/_team/earnedit/dto/auth/SignUpRequestDto.java
  src/main/java/_team/earnedit/dto/auth/SignUpResponseDto.java
  src/main/java/_team/earnedit/dto/jwt/JwtUserInfoDto.java
  src/main/java/_team/earnedit/dto/profile/NicknameRequestDto.java
  src/main/java/_team/earnedit/dto/profile/ProfileImageRequestDto.java
  src/main/java/_team/earnedit/dto/profile/ProfileInfoResponseDto.java
  src/main/java/_team/earnedit/dto/profile/SalaryRequestDto.java
  src/main/java/_team/earnedit/dto/profile/SalaryResponseDto.java
  src/main/java/_team/earnedit/dto/socialLogin/AppleSignInRequestDto.java
  src/main/java/_team/earnedit/dto/socialLogin/AppleUserInfoDto.java
  src/main/java/_team/earnedit/dto/socialLogin/KakaoSignInRequestDto.java
  src/main/java/_team/earnedit/dto/socialLogin/KakaoUserInfoDto.java
  src/main/java/_team/earnedit/dto/term/TermRequestDto.java
Labels: 문서

#57 doc/swagger : 컨트롤러 api그룹 태그 추가
  src/main/java/_team/earnedit/controller/AuthController.java
  src/main/java/_team/earnedit/controller/EmailVerificationController.java
  src/main/java/_team/earnedit/controller/PasswordResetController.java
  src/main/java/_team/earnedit/controller/ProfileController.java
  src/main/java/_team/earnedit/controller/UserController.java
Labels: 문서

#58 ref: (프론트 요청) 빈 배열 예외 제거
  src/main/java/_team/earnedit/global/ErrorCode.java
  src/main/java/_team/earnedit/service/WishService.java
Labels: 리팩터링

#62 Ref/admin 테마별 필터링 기능 추가, Item.theme -> Item.category로 수정
  src/main/java/_team/earnedit/controller/admin/ItemAdminController.java
  src/main/java/_team/earnedit/controller/admin/PuzzleSlotAdminController.java
  src/main/java/_team/earnedit/dto/item/ItemRequest.java
  src/main/java/_team/earnedit/entity/Item.java
  src/main/java/_team/earnedit/repository/PuzzleSlotRepository.java
  src/main/java/_team/earnedit/service/admin/item/ItemServiceImpl.java
  src/main/resources/templates/admin/item-form.html
  src/main/resources/templates/admin/item-list.html
  src/main/resources/templates/admin/puzzle-slot-list.html
Labels: 리팩터링, 기능

#63 Feat/colum : User 엔티티에 출석체크 컬럼추가, CheckInResetScheduler 구현
  src/main/java/_team/earnedit/entity/User.java
  src/main/java/_team/earnedit/global/scheduler/CheckInResetScheduler.java
  src/main/java/_team/earnedit/repository/UserRepository.java
Labels: 기능

#65 fix : 비밀번호찾기 기능에서 local로 가입된 계정만 처리
  src/main/java/_team/earnedit/repository/UserRepository.java
  src/main/java/_team/earnedit/service/PasswordResetService.java
Labels: 버그

#66 Bug/puzzle 퍼즐 정보 조회 API 버그 수정, 조각 중복 추가 버그 수정
  src/main/java/_team/earnedit/controller/PuzzleController.java
  src/main/java/_team/earnedit/dto/puzzle/PuzzleResponse.java
  src/main/java/_team/earnedit/dto/term/TermRequestDto.java
  src/main/java/_team/earnedit/service/DailyCheckService.java
  src/main/java/_team/earnedit/service/PuzzleService.java
Labels: 버그, 리팩터링

#68 Ref/main-star-puzzle 메인, 스타, 퍼즐 서비스 리팩토링(메서드 분리, Mapper)
  src/main/java/_team/earnedit/controller/StarController.java
  src/main/java/_team/earnedit/mapper/MainPageMapper.java
  src/main/java/_team/earnedit/mapper/PieceMapper.java
  src/main/java/_team/earnedit/mapper/PuzzleMapper.java
  src/main/java/_team/earnedit/mapper/StarMapper.java
  src/main/java/_team/earnedit/repository/StarRepository.java
  src/main/java/_team/earnedit/service/MainService.java
  src/main/java/_team/earnedit/service/PuzzleService.java
  src/main/java/_team/earnedit/service/StarService.java
  src/main/java/_team/earnedit/service/WishService.java
Labels: 리팩터링

#73 Ref/debug Star, Wish, FileUpload, DailyCheck 서비스 로깅 작업
  src/main/java/_team/earnedit/controller/StarController.java
  src/main/java/_team/earnedit/controller/WishController.java
  src/main/java/_team/earnedit/service/DailyCheckService.java
  src/main/java/_team/earnedit/service/FileUploadService.java
  src/main/java/_team/earnedit/service/StarService.java
  src/main/java/_team/earnedit/service/WishService.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application.yaml
Labels: 리팩터링

#76 Ref/codes : 도메인 예외 메서드 분리
  src/main/java/_team/earnedit/global/util/EntityFinder.java
  src/main/java/_team/earnedit/service/AuthService.java
  src/main/java/_team/earnedit/service/ProfileService.java
Labels: 리팩터링

#77 Ref/daily-check 출석체크 서비스 코드 리팩토링
  src/main/java/_team/earnedit/controller/StarController.java
  src/main/java/_team/earnedit/service/DailyCheckService.java
Labels: 리팩터링

#79 Ref/security : JWT 인증/인가 구조 전면 정비 (+블랙리스트/헤더강화/엔드포인트 정리)
  src/main/java/_team/earnedit/config/security/CustomAccessDeniedHandler.java
  src/main/java/_team/earnedit/config/security/JwtFilterConfig.java
  src/main/java/_team/earnedit/config/security/SecurityConfig.java
  src/main/java/_team/earnedit/controller/FileUploadController.java
  src/main/java/_team/earnedit/global/jwt/JwtAuthFilter.java
  src/main/java/_team/earnedit/global/jwt/JwtUtil.java
  src/main/java/_team/earnedit/service/AuthService.java
Labels: 리팩터링, 기능
